---
title: "subcatchment_processing"
author: "Kristin Gill and Genevieve Chiong"
date: "12/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(sf)
```

Subcatchments
```{r}
subcatchments <- read_sf(here("subcatchment_processing", "data", "subcatchments", "subcatchment_vertices.shp")) %>% 
  select(subcatchme, geometry)

subcatchment_coordinates <- subcatchments %>% 
  mutate(lat = unlist(map(geometry,1)),
         long = unlist(map(geometry,2))) %>% 
  rename(objectid = subcatchme) %>% 
  select(objectid, lat, long)
```

Impervious Surfaces Percentage
```{r}
impervious_percentage <- read_csv(here("subcatchment_processing", "data", "impervious_kuliouou_percentage.csv")) %>% 
  rename(percent_impervious = PERCENTAGE) %>% 
  select("subcatchments_recon_aa_20211027_Id", "percent_impervious")
```

Slope Percentage
```{r}
slope_percentage <- read_csv(here("subcatchment_processing", "data", "slope_weighted_kuliouou.csv")) %>% 
  select("subcatchments_recon_aa_20211027_Id", "mean_slope")
```

Curve Number Percentage 
```{r}
curve_numbers_percentage <- read_csv(here("subcatchment_processing", "data", "curve_number_weighted_kuliouou.csv")) %>% 
  select("subcatchments_recon_aa_20211027_Id", "mean_cn")
```

Merge Data
```{r}
merge_cn_slope <- merge(curve_numbers_percentage, slope_percentage, by = "subcatchments_recon_aa_20211027_Id")

attributes <- merge(merge_cn_slope, impervious_percentage, by = "subcatchments_recon_aa_20211027_Id", all.x = TRUE) %>% 
  rename(objectid = subcatchments_recon_aa_20211027_Id)

attributes[is.na(attributes)] <- 0 
```

Subcatchment Area and Width
```{r}
subcatchment_area <- read_csv(here("subcatchment_processing", "data", "subcatchments_area_sqft.csv")) %>% 
  rename(objectid = OBJECTID) %>% 
  rename(area_sqft = Shape_Area) %>% 
  select(objectid, area_sqft)

subcatchment_length <- read_csv(here("subcatchment_processing", "data", "lengths_subcatchments.csv")) %>% 
  rename(objectid = OBJECTID) %>% 
  rename(length_ft = LENGTH) %>% 
  select(objectid, length_ft)

subcatchment_width <- merge(subcatchment_area, subcatchment_length, by.x = "objectid", all.x= TRUE) %>% 
  mutate(width_ft = area_sqft/length_ft) %>% 
  select(objectid, width_ft)
```

Subcatchments Input File
```{r}
coordinates_attributes <- merge(subcatchment_coordinates, attributes, by = "objectid") %>% distinct (objectid, .keep_all = TRUE) 

coordinates_attributes <- merge(coordinates_attributes, subcatchment_area, by = "objectid")

coordinates_attributes <- merge(coordinates_attributes, subcatchment_width, by = "objectid")

subc <- coordinates_attributes %>%
  mutate(area_acre = area_sqft*0.0000229568) %>% 
  rename(area = area_acre,
    imperv = percent_impervious,
    name = objectid,
    slope = mean_slope,
    curve_number = mean_cn) %>% 
  distinct() %>% 
  mutate(width = case_when(
    width_ft > 400 ~ 400,
    width_ft <= 400 ~ width_ft 
  )) %>% 
  st_set_geometry(NULL)

subc[is.na(subc)] <- 400 

#add columns for "subcatchments" file. 
subc$rain_gage <- "R1" 
subc$outlet <- "J1" 
subc$curblen <- 0

#arrange
subc_file <- subc %>% 
  select(
    name, 
    rain_gage, 
    outlet, 
    area, 
    imperv, 
    width, 
    slope, 
    curblen
    ) %>% 
  distinct(name, .keep_all = TRUE)

write.csv(subc_file, here("subcatchment_processing","output", "inp_subcatchments.csv"), row.names = FALSE)
```

Sub Areas
```{r}
suba <- subc_file %>% 
  select(name) %>% 
  rename(subcatchment = name) %>% 
  distinct()

suba$n_imperv <- 0.01 #manning's n for impervious surfaces - values from SWMM Manual

suba$n_perv <- 0.4 #manning's n for pervious (natural) surfaces. 0.4 for forested subcatchments. 
#Later, identify urban subcatchments and input 0.15. - values from SWMM Manual  

suba$s_imperv <- 0.2 #impervious surface depth of depression storage (in) - values in SWMM Manual

suba$s_perv <- 0.3 #pervious (natural) surface depth of depression storage - values in SWMM manual

suba$pctzero <- 0
suba$RouteTo <- "OUTLET"

#n is for Manning's n, and s is for Depth of Depression Storage.

write.csv(suba, here("subcatchment_processing", "output", "inp_subareas.csv"), row.names = FALSE)
```

Infiltration
```{r}
infil <- subc %>% 
  select(name,
         curve_number) %>% 
  rename(subcatchment = name) %>% 
  distinct()

infil$Blank <- 0.5 #this is conductivity, however this may have been depreciated in the model
infil$DryTime <- 7 #units in days

write.csv(infil, here("subcatchment_processing", "output", "inp_infiltration.csv"), row.names = FALSE)
```

Polygons
```{r}
polygons <- subcatchment_coordinates %>%
  rename(name = objectid,
         y = lat,
         x = long) %>% 
  select(name, x,y) %>% 
  rename(subcatchment = name) %>% 
  st_set_geometry(NULL) %>% 
  distinct()

write.csv(polygons, here("subcatchment_processing", "output", "inp_polygons.csv"), row.names = FALSE)
```

