---
title: "Paiko vs Wailupe Exploration"
author: "Elmera Azadpour"
date: "10/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(tidyverse)
library(here)
library(dplyr)
library(ggplot2)
```

## Read in Paiko and Wailupe Valley School (WVS)
```{r}
paiko_76_rain <- read.csv("NOAA_Paiko_76.csv")
wailupe_08_rain <-  read.csv("NOAA_WailupeHawaiiKai_08.csv")
wailupe_77_rain <-  read.csv("NOAA_WailupeHawaiiKai_77.csv")

##Use lubridate to clean up the dates and times
wailupe_08_rain$DATE <- ymd(wailupe_08_rain$DATE)
wailupe_77_rain$DATE <- ymd(wailupe_77_rain$DATE)
paiko_76_rain$DATE <- mdy(paiko_76_rain$DATE)
```

## Data Tidying
```{r}
## for wailupe 1977-2014
wailupe_tidy_77 <- wailupe_77_rain %>% 
  rename(station = STATION, station_name = STATION_NAME, elevation = ELEVATION, 
         lat = LATITUDE, lon = LONGITUDE, date = DATE, time = TIME, qgag = QGAG, 
         qgag_flag = Measurement.Flag, qgag_qual = Quality.Flag, qgag_units = Units, 
         qpcp = QPCP, qpcp_flag = Measurement.Flag.1, qpcp_qual = Quality.Flag.1, 
         qpcp_units = Units.1) %>% #renames columns
  filter(station_name == "WAILUPE VALLEY SCHOOL 723.6 HI US") %>% #filter to Wailupe gauge only
  filter(qpcp != "-9999",
         qpcp != "999",
         qpcp != "999.99",
         qpcp_flag != "g",
         qpcp_flag != "{",
         qpcp_flag != "}",
         qpcp_flag != "[",
         qpcp_flag != "]",
         qgag != "-9999.00",
         qgag != "-9999",
         qgag_flag != "g",
         qgag_flag != "V",
         qgag_flag != "P",
         qgag_flag != "{",
         qgag_flag != "}",
         qgag_flag != "[",
         qgag_flag != "]") ## removes all flagged data

## wailupe 2008- 2021
wailupe_tidy_08 <- wailupe_08_rain %>% 
  rename(station = STATION, station_name = STATION_NAME, elevation = ELEVATION, 
         lat = LATITUDE, lon = LONGITUDE, date = DATE, time = TIME, qgag = QGAG, 
         qgag_flag = Measurement.Flag, qgag_qual = Quality.Flag, qgag_units = Units, 
         qpcp = QPCP, qpcp_flag = Measurement.Flag.1, qpcp_qual = Quality.Flag.1, 
         qpcp_units = Units.1) %>% #renames columns
  filter(station_name == "WAILUPE VALLEY SCHOOL 723.6 HI US") %>% #filter to Wailupe gauge only
  filter(qpcp != "-9999",
         qpcp != "999",
         qpcp != "999.99",
         qpcp_flag != "g",
         qpcp_flag != "{",
         qpcp_flag != "}",
         qpcp_flag != "[",
         qpcp_flag != "]",
         qgag != "-9999.00",
         qgag != "-9999",
         qgag_flag != "g",
         qgag_flag != "V",
         qgag_flag != "P",
         qgag_flag != "{",
         qgag_flag != "}",
         qgag_flag != "[",
         qgag_flag != "]") ## removes all flagged data



## paiko 1976- 2020
paiko_tidy_76 <- paiko_76_rain %>% 
  rename(station = STATION, station_name = NAME, elevation = ELEVATION, 
         lat = LATITUDE, lon = LONGITUDE, date = DATE, qpcp = PRCP) %>% #renames columns
  filter(station_name == "PAIKO DRIVE 723.4, HI US") 

```

```{r}
wailupe_daily_77 <- wailupe_tidy_77 %>%  
  group_by(date) %>%
  summarize(
    daily_pcp = sum(qpcp),
    daily_vol = sum(qgag)) ## gives total summed precip data per day. HT is given in inches.

paiko_daily_76 <- paiko_tidy_76 %>%  
  group_by(date) %>%
  summarize(
    daily_pcp = sum(qpcp)) 

```


## explore time series 
```{r}
wailupe_daily_77$date <- ymd(wailupe_daily_77$date)
paiko_daily_76$date <- ymd(paiko_daily_76$date)

ggplot() +
  geom_line(data = wailupe_daily_77, aes(x=date, y=daily_pcp), size = 0.5,color="red") +
  geom_line(data = paiko_daily_76, aes(x=date, y=daily_pcp), size = 0.5, color = "seagreen") +
  theme_minimal() + 
  scale_y_continuous(breaks=seq(0,7,1)) +
  scale_x_date(date_breaks = "2 years", date_labels = "%Y") +
  ggtitle("NOAA Daily Total Precip: Wailupe Fire Station and Paiko Drive")

```

```{r}
# Wailupe Valley School vs. Paiko Drive
paiko_daily_76 <- paiko_daily_76 %>% 
  mutate(year = year(date)) %>% 
  mutate(month = month(date)) %>% 
  mutate(day = day(date))

paiko_january_2005 <- paiko_daily_76 %>% 
  filter(year == 2005) %>% 
  filter(month == 1)

wailupe_daily_77 <- wailupe_daily_77 %>% 
  mutate(year = year(date)) %>% 
  mutate(month = month(date)) %>% 
  mutate(day = day(date))

wailupe_january_2005 <- wailupe_daily_77 %>% 
  filter(year == 2005) %>% 
  filter(month == 1)

#plot January 2005
ggplot() +
  geom_line(data = paiko_january_2005, aes(x = day,
                                           y = daily_pcp)) +
  geom_point(data = paiko_january_2005, aes(x = day,
                                           y = daily_pcp)) +
  geom_line(data = wailupe_january_2005, aes(x = day,
                                             y = daily_pcp)) +
  geom_point(data = wailupe_january_2005, aes(x = day,
                                             y = daily_pcp)) +
  theme_minimal()

#plot December 2011
paiko_december_2011 <- paiko_daily_76 %>% 
  filter(year == 2011) %>% 
  filter(month == 12) %>% 
  filter(day <= 24)

wailupe_december_2011 <- wailupe_daily_77 %>% 
  filter(year == 2011) %>% 
  filter(month == 12)

ggplot() +
  geom_line(data = paiko_december_2011, aes(x = day,
                                           y = daily_pcp,
                                           color = "blue")) +
  geom_point(data = paiko_december_2011, aes(x = day,
                                           y = daily_pcp),
             color = "blue") +
  geom_line(data = wailupe_december_2011, aes(x = day,
                                             y = daily_pcp,
                                             color = "red")) +
  geom_point(data = wailupe_december_2011, aes(x = day,
                                             y = daily_pcp),
             color = "red") +
  scale_color_manual(values = c("blue", "red"), labels = c("Paiko", "Wailupe Valley School")) +
  theme_minimal() +
  theme(legend.title = element_blank()) +
  labs(x = "Day",
       y = "Daily Precipitation",
       title = "December 2011")

# compare yearly
paiko_yearly <- paiko_daily_76 %>% 
  group_by(year) %>% 
  mutate(sum = sum(daily_pcp)) %>% 
  select(year, sum) %>% 
  distinct() %>% 
  drop_na() %>% 
  filter(year >= 1996 & year <= 2013)

wailupe_yearly <- wailupe_daily_77 %>% 
  group_by(year) %>% 
  mutate(sum = sum(daily_pcp)) %>% 
  select(year, sum) %>% 
  distinct() %>% 
  drop_na()

ggplot() +
  geom_line(data = paiko_yearly, aes(x = year,
                                     y = sum,
                                     color = "blue")) +
  geom_point(data = paiko_yearly, aes(x = year,
                                     y = sum),
             color = "blue") +
  geom_line(data = wailupe_yearly, aes(x = year,
                                     y = sum,
                                     color = "red")) +
  geom_point(data = wailupe_yearly, aes(x = year,
                                     y = sum),
             color = "red") +
  scale_color_manual(values = c("blue", "red"), labels = c("Paiko", "Wailupe Valley School")) +
  theme_minimal() +
  theme(legend.title = element_blank()) +
  labs(x = "Year",
       y = "Sum of Precipitation")
```

```{r}
# all data
paiko_wailupe_comp <- merge(paiko_daily_76, wailupe_daily_77, by = "date")

ggplot(data = paiko_wailupe_comp, aes(x = daily_pcp.x,
                                      y = daily_pcp.y)) +
  geom_point() +
  theme_minimal() +
  labs(x = "Paiko",
       y = "Wailupe Valley School")

# for a specified stormy period
paiko_wailupe_comp_2008_storm <- paiko_wailupe_comp %>% 
  filter(year.x == 2008) %>% 
  filter(month.x == 12)

ggplot(data = paiko_wailupe_comp_2008_storm, aes(x = daily_pcp.x,
                                      y = daily_pcp.y)) +
  geom_point() +
  theme_minimal() +
  theme_minimal() +
  labs(x = "Paiko",
       y = "Wailupe Valley School")
 
# for a specified year: 2013
paiko_wailupe_comp_2013 <- paiko_wailupe_comp %>% 
  filter(year.x == 2013)

ggplot(data = paiko_wailupe_comp_2013, aes(x = daily_pcp.x,
                                      y = daily_pcp.y)) +
  geom_point() +
  theme_minimal() +
  theme_minimal() +
  labs(x = "Paiko",
       y = "Wailupe Valley School")

# for a specified year: 2008
paiko_wailupe_comp_2008 <- paiko_wailupe_comp %>% 
  filter(year.x == 2008)

ggplot(data = paiko_wailupe_comp_2008, aes(x = daily_pcp.x,
                                      y = daily_pcp.y)) +
  geom_point() +
  theme_minimal() +
  theme_minimal() +
  labs(x = "Paiko",
       y = "Wailupe Valley School")

# 2002 January
paiko_wailupe_comp_2002 <- paiko_wailupe_comp %>% 
  filter(year.x == 2002) %>% 
  filter(month.x == 1)

ggplot(data = paiko_wailupe_comp_2002, aes(x = daily_pcp.x,
                                      y = daily_pcp.y)) +
  geom_point() +
  theme_minimal() +
  theme_minimal() +
  labs(x = "Paiko",
       y = "Wailupe Valley School")

# 2011 December
paiko_wailupe_comp_2011 <- paiko_wailupe_comp %>% 
  filter(year.x == 2011) %>% 
  filter(month.x == 12)

ggplot(data = paiko_wailupe_comp_2011, aes(x = daily_pcp.x,
                                      y = daily_pcp.y)) +
  geom_point() +
  theme_minimal() +
  theme_minimal() +
  labs(x = "Paiko",
       y = "Wailupe Valley School",
       title = "Daily Precipitation December 2011") +
  geom_smooth(method='lm', formula = y~x) +
  stat_regline_equation(label.x = 0.25,
                        label.y = 1) +
  stat_cor(label.x = 0.25,
           label.y = 0.8)

# yearly comparison
paiko_wailupe_comp_yearly <- merge(paiko_yearly, wailupe_yearly, by = "year")

ggplot(data = paiko_wailupe_comp_yearly, aes(x = sum.x,
                                      y = sum.y)) +
  geom_point() +
  theme_minimal() +
  theme_minimal() +
  labs(x = "Paiko",
       y = "Wailupe Valley School",
       title = "Yearly Precipitation: 1996-2013") +
  geom_smooth(method='lm', formula = y~x) +
  stat_regline_equation(label.x = 10,
                        label.y = 33) +
  stat_cor(label.x = 10,
           label.y = 30)
```

```{r}
# continuing to look for storms
paiko_match <- paiko_daily_76 %>% 
  filter(year >= 2009 & year <= 2010) %>% 
  filter(daily_pcp > 0)

wailupe <- wailupe_daily_77 %>% 
  filter(year >= 2009 & year <= 2010) %>% 
  filter(daily_pcp > 0)

# Jaunary 4-10, 1996
wailupe_jan_1996 <- wailupe_daily_77 %>% 
  filter(year == 1996) %>% 
  filter(month == 1)

paiko_jan_1996 <- paiko_daily_76 %>% 
  filter(year == 1996) %>% 
  filter(month == 1) %>% 
  filter(day %in% c(4,5,7,10,18,19,24,25,27,28,30))

ggplot() +
  geom_line(data = wailupe_jan_1996, aes(x = day,
                                         y = daily_pcp,
                                         color = "blue")) +
  geom_line(data = paiko_jan_1996, aes(x = day,
                                       y = daily_pcp,
                                       color = "red")) +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red"), labels = c("Wailupe", "Paiko")) +
  theme(legend.title = element_blank()) +
  labs(title = "Jaunary 4-10, 1996")

# November 12-16, 1996
wailupe_nov_1996 <- wailupe_daily_77 %>% 
  filter(year == 1996) %>% 
  filter(month == 11) %>% 
  filter(day %in% c(11:17))

paiko_nov_1996 <- paiko_daily_76 %>% 
  filter(year == 1996) %>% 
  filter(month == 11) %>% 
  filter(day %in% c(11:17))

ggplot() +
  geom_line(data = wailupe_nov_1996, aes(x = day,
                                         y = daily_pcp,
                                         color = "blue")) +
  geom_line(data = paiko_nov_1996, aes(x = day,
                                       y = daily_pcp,
                                       color = "red")) +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red"), labels = c("Wailupe", "Paiko")) +
  theme(legend.title = element_blank()) +
  labs(title = "November 12-16, 1996")

# January 28-31, 2005
wailupe_jan_2005 <- wailupe_daily_77 %>% 
  filter(year == 2005) %>% 
  filter(month == 1) %>% 
  filter(day %in% c(28:31))

paiko_jan_2005 <- paiko_daily_76 %>% 
  filter(year == 2005) %>% 
  filter(month == 1) %>% 
  filter(day %in% c(28:31))

ggplot() +
  geom_line(data = wailupe_jan_2005, aes(x = day,
                                         y = daily_pcp,
                                         color = "blue")) +
  geom_line(data = paiko_jan_2005, aes(x = day,
                                       y = daily_pcp,
                                       color = "red")) +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red"), labels = c("Wailupe", "Paiko")) +
  theme(legend.title = element_blank()) +
  labs(title = "January 28-31, 2005")
```

```{r}
### 2009 - 2010 (lines up with the streamgage data)
# March 6-15, 2009
wailupe_mar_2009 <- wailupe_daily_77 %>% 
  filter(year == 2009) %>% 
  filter(month == 3) %>% 
  filter(day %in% c(6:15))

paiko_mar_2009 <- paiko_daily_76 %>% 
  filter(year == 2009) %>% 
  filter(month == 3) %>% 
  filter(day %in% c(6:15))

ggplot() +
  geom_line(data = wailupe_mar_2009, aes(x = day,
                                         y = daily_pcp,
                                         color = "blue")) +
  geom_point(data = wailupe_mar_2009, aes(x = day,
                                         y = daily_pcp),
             color = "blue") +
  geom_line(data = paiko_mar_2009, aes(x = day,
                                       y = daily_pcp,
                                       color = "red")) +
  geom_point(data = paiko_mar_2009, aes(x = day,
                                       y = daily_pcp),
             color = "red") +
  
  theme_minimal() +
  scale_color_manual(values = c("blue", "red"), labels = c("Wailupe", "Paiko")) +
  theme(legend.title = element_blank()) +
  labs(title = "March 6-15, 2009")

# December 9-25, 2010
wailupe_dec_2010 <- wailupe_daily_77 %>% 
  filter(year == 2010) %>% 
  filter(month == 12) %>% 
  filter(day %in% c(9:25))

paiko_dec_2010 <- paiko_daily_76 %>% 
  filter(year == 2010) %>% 
  filter(month == 12) %>% 
  filter(day %in% c(9:25))

ggplot() +
  geom_line(data = wailupe_dec_2010, aes(x = day,
                                         y = daily_pcp,
                                         color = "blue")) +
  geom_point(data = wailupe_dec_2010, aes(x = day,
                                         y = daily_pcp),
             color = "blue") +
  geom_line(data = paiko_dec_2010, aes(x = day,
                                       y = daily_pcp,
                                       color = "red")) +
  geom_point(data = paiko_dec_2010, aes(x = day,
                                       y = daily_pcp),
             color = "red") +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red"), labels = c("Wailupe", "Paiko")) +
  theme(legend.title = element_blank()) +
  labs(title = "December 9-25, 2010")

# October - November, 2010
wailupe_nov_2010 <- wailupe_daily_77 %>% 
  filter(year == 2010) %>% 
  filter(month %in% c(10,11)) %>% 
  filter(date >= "2010-10-29" & date <= "2010-11-05")

paiko_nov_2010 <- paiko_daily_76 %>% 
 filter(year == 2010) %>% 
  filter(month %in% c(10,11)) %>% 
  filter(date >= "2010-10-29" & date <= "2010-11-05")

ggplot() +
  geom_line(data = wailupe_nov_2010, aes(x = date,
                                         y = daily_pcp,
                                         color = "blue")) +
  geom_point(data = wailupe_nov_2010, aes(x = date,
                                         y = daily_pcp),
             color = "blue") +
  geom_line(data = paiko_nov_2010, aes(x = date,
                                       y = daily_pcp,
                                       color = "red")) +
  geom_point(data = paiko_nov_2010, aes(x = date,
                                       y = daily_pcp),
            color = "red") +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red"), labels = c("Wailupe", "Paiko")) +
  theme(legend.title = element_blank()) +
  labs(title = "October - November, 2010")

# all 2009
wailupe_2009 <- wailupe_daily_77 %>% 
  filter(year == 2009)

paiko_2009 <- paiko_daily_76 %>% 
 filter(year == 2009)

ggplot() +
  geom_line(data = wailupe_2009, aes(x = date,
                                         y = daily_pcp,
                                         color = "blue")) +
  geom_line(data = paiko_2009, aes(x = date,
                                       y = daily_pcp,
                                       color = "red")) +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red"), labels = c("Wailupe", "Paiko")) +
  theme(legend.title = element_blank()) +
  labs(title = "2009")

# correlation plot 2009
wailupe_paiko_2009 <- merge(paiko_2009, wailupe_2009, by = "date")

ggplot(data = wailupe_paiko_2009, aes(x = daily_pcp.x,
                                      y = daily_pcp.y)) +
  geom_point() +
  theme_minimal() +
  labs(x = "Paiko",
       y = "Wailupe Valley School",
       title = "Precipitation 2009") +
  geom_smooth(method='lm', formula = y~x)

# November - December, 2009
wailupe_nov_2009 <- wailupe_daily_77 %>% 
  filter(year == 2009) %>%
  filter(date >= "2009-11-29" & date < "2009-12-15")

paiko_nov_2009 <- paiko_daily_76 %>% 
  filter(year == 2009) %>%
  filter(date >= "2009-11-29" & date <= "2009-12-03")

ggplot() +
  geom_line(data = wailupe_nov_2009, aes(x = date,
                                         y = daily_pcp,
                                         color = "blue")) +
  geom_line(data = paiko_nov_2009, aes(x = date,
                                       y = daily_pcp,
                                       color = "red")) +
  geom_point(data = wailupe_nov_2009, aes(x = date,
                                         y = daily_pcp),
             color = "blue") +
  geom_point(data = paiko_nov_2009, aes(x = date,
                                       y = daily_pcp),
             color = "red") +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red"), labels = c("Wailupe", "Paiko")) +
  theme(legend.title = element_blank()) +
  labs(title = "November - December, 2009")

# all 2010
wailupe_2010 <- wailupe_daily_77 %>% 
  filter(year == 2010)

paiko_2010 <- paiko_daily_76 %>% 
 filter(year == 2010)

ggplot() +
  geom_line(data = wailupe_2010, aes(x = date,
                                         y = daily_pcp,
                                         color = "blue")) +
  geom_line(data = paiko_2010, aes(x = date,
                                       y = daily_pcp,
                                       color = "red")) +
  theme_minimal() +
  scale_color_manual(values = c("blue", "red"), labels = c("Wailupe", "Paiko")) +
  theme(legend.title = element_blank()) +
  labs(title = "2010")

# correlation plot 2010
wailupe_paiko_2010 <- merge(paiko_2010, wailupe_2010, by = "date")

ggplot(data = wailupe_paiko_2009, aes(x = daily_pcp.x,
                                      y = daily_pcp.y)) +
  geom_point() +
  theme_minimal() +
  labs(x = "Paiko",
       y = "Wailupe Valley School",
       title = "Precipitation 2010") +
  geom_smooth(method='lm', formula = y~x)
```


```{r}
SKN_processed_stations =  read.csv(here("Paiko","ProcessedOriginalData_Data_in.csv"))%>% 
  pivot_longer(cols = Jan:Dec, names_to = "Month", values_to = "pcp_in") 

RA_paiko_wailupe_investigation <- SKN_processed_stations %>% 
   filter(SKN %in% c(723.4, 723.0)) # Wailupe = 723; Paiko = 723.4

RA_paiko <- RA_paiko_wailupe_investigation %>% 
  filter(SKN %in% c(723.4)) 

RA_wailupe <- RA_paiko_wailupe_investigation %>% 
  filter(SKN %in% c(723)) 

RA_paiko$Month = factor(RA_paiko$Month, levels=c('Jan','Feb','Mar','Apr', 'May','Jun','Jul', 'Aug','Sep','Oct','Nov','Dec'))
RA_wailupe$Month = factor(RA_wailupe$Month, levels=c('Jan','Feb','Mar','Apr', 'May','Jun','Jul', 'Aug','Sep','Oct','Nov','Dec'))

ggplot() +
  geom_line(data = RA_wailupe, aes(x=Year, y=pcp_in), size = 0.5, color="red") +
  geom_line(data = RA_paiko, aes(x=Year, y=pcp_in), size = 0.5, color = "seagreen") +
  theme_minimal() + 
  scale_y_continuous(breaks=seq(0,25,5)) +
  scale_x_continuous(breaks=seq(1920,2010,10)) +
  labs( y = "Precipitation (in)", x= "Date") +
  ggtitle("Rainfall Atlas Monthly Total Precip: Wailupe Fire Station and Paiko Drive") +
  facet_wrap(~Month)

```
## scatterplot of wailupe vs paiko 
```{r}
merged_precip <- merge(paiko_daily_76, wailupe_daily_77, by = "date") %>%  select(-daily_vol) %>% 
   rename(wailupe_rain_in = daily_pcp.y, paiko_rain_in = daily_pcp.x) %>% 
  filter(date >= as.Date("1996-01-04") & date <= as.Date("1996-12-31"))

 
ggplot(data = merged_precip, aes(x =paiko_rain_in, y= wailupe_rain_in)) + 
  geom_point() +
  theme_minimal() 

ggplot(data = merged_precip, aes(x =paiko_rain_in, y= wailupe_rain_in)) + 
  geom_point() +
  theme_minimal() +
  scale_x_continuous(limits=c(0,1)) +
  scale_y_continuous(limits=c(0,1)) 
```

